### ISSUE TITLE
Modify BTC.b to BTC bridge UI to reflect recent changes in bridging delay

### ISSUE THREAD

**Issue by Lamaw** [ava-labs/avalanche-bridge-resources#38]
In discord "bridging-support" channel, several users enquired about late/missing bridging transactions from avalanche C chain to Bitcoin network.
It appears that a bridging delay was introduced to answer regulatory concerns. 
Can this delay be reflected in the core UI so the bridge users can **knowingly** engage in locking their BTC for 12+ hours when bridging ?

**Comment by michaelkaplan13** [comment]
Sorry we just saw this issue now (this repo is not under active development). I believe this disclaimer was added to the Core UI last fall. Even better though, the Core wallet is now open source, you can add any future issues/feature requests you have for it in that repository.

https://github.com/ava-labs/core-extension
