### ISSUE TITLE
Are there any bugs in the BridgeToken.sol?

### ISSUE THREAD

**Issue by xuebingqing** [ava-labs/avalanche-bridge-resources#40]
## Description
When we recently used the fuzz testing tool, we scanned the contract BridgeToken.sol. We found some issues and wanted to confirm with you.
```sol
function swap(address token, uint256 amount) public {
        require(isContract(token), "Token is not a contract.");
        require(
            swapTokens[token].tokenContract != address(0),
            "Swap token is not a contract."
        );
        require(
            amount <= swapTokens[token].supply,
            "Swap amount is more than supply."
        );

        // Update the allowed swap amount.
        swapTokens[token].supply = swapTokens[token].supply - amount;

        // Burn the old token.
        ERC20Burnable swapToken = ERC20Burnable(
            swapTokens[token].tokenContract
        );
        swapToken.burnFrom(msg.sender, amount);

        // Mint the new token.
        _mint(msg.sender, amount);

        emit Swap(token, amount);
    }
```
As you can see, token is used as input and is controllable by the user. If there is malicious input later and implement the ERC20Burnable interface standard, it calls burnFrom without checking the token address. Are there any problems?

**Comment by michaelkaplan13** [comment]
Thanks for raising this question, and sorry it went unnoticed for so long.

The reason why this is not an issue/bug with the contract is that `token` must be in the `swapTokens` mapping, which can only be added to via the bridge address.

I agree there are more robust ways that this could be implemented, but as is it should not present any issue.
