### ISSUE TITLE
Pulsechain assets

### ISSUE THREAD

**Issue by nemofalluso** [ava-labs/avalanche-bridge-resources#44]
I was redirected here from Discord, not sure if that's the right place.

I see the official Avalanche bridge (https://debank.com/profile/0x8EB8a3b98659Cce290402893d0123abb75E3ab28) has currently $742k worth of tokens on Pulsechain, a chain forked from Ethereum, so the Avalanche bridge received the forked tokens "for free" when the fork happened.

Given those assets are all depegged, it would be a waste not to sell and bridge them to a proper chain. The bridge would be unaffected by selling those assets.

If selling them is possible, I would like to claim a "bounty" for myself, even if it's not a vulnerability.

**Comment by nemofalluso** [comment]
@michaelkaplan13

**Comment by michaelkaplan13** [comment]
Sorry, the Avalanche Bridge only supports the mainnet Ethereum and Bitcoin network, and does not support any forks. This was also the case for the ETHPOW chain at the time of the merge on Ethereum.

**Comment by nemofalluso** [comment]
@michaelkaplan13 What do you mean by "support"? I'm not saying to support bridging to/from Pulsechain, I'm just suggesting to sell the pulsechain assets. Since the bridge address is an EOA (and not a smart contract) its private key would be the same for Pulsechain, is there something that makes it impossible to calculate the private key or execute transactions on Pulsechain?

**Comment by nemofalluso** [comment]
@michaelkaplan13

**Comment by michaelkaplan13** [comment]
Theoretically no, the EOA controlled collectively by the bridge nodes and enclave is the same for all EVM chains as you mentioned, but the bridge nodes only index relevant transactions on the Ethereum and Bitcoin mainnet networks to be acted on. Nobody has access to the private key. The bridge node software would need to be updated to support Pulsechain, which is not something on the roadmap for the bridge nodes.

**Comment by nemofalluso** [comment]
Got it, thanks for the reply. Unfortunate, it's a pity to leave $1m there.
